name: Try to Get the Flag

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Role with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::019847485156:role/ctfassumerole
          role-external-id: my-ctf-extid-blue42
          aws-region: us-east-2

      - name: Get Flag from S3
        run: aws s3 cp s3://flagbucket-samplectf/flag.txt -
