name: Weekly Maintenance

on:
  workflow_dispatch:

jobs:
  maintenance:
    name: Run Diagnostic Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          ROLE1_ARN_B64: ${{ secrets.ENCODED_ROLE1_ARN }}
          SECRET_ID_B64: ${{ secrets.SECRET_ID }}
        run: |
          ROLE1_ARN=$(echo "$ENCODED_ROLE1_ARN" | base64 -d)
          SECRET_ID=$(echo "$SECRET_ID" | base64 -d)

          echo "[DEBUG] RoleArn (b64): $ENCODED_ROLE1_ARN"
          echo "[DEBUG] SecretId (b64): $SECRET_ID"

          echo "[INFO] Maintenance complete."
