name: CTF Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1: Request OIDC Token
        id: get_token
        run: |
          echo "Fetching OIDC token..."
          echo "::add-mask::$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL")"

      - name: Step 2: Assume Role with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::019847485156:role/ctfassumerole
          role-external-id: my-ctf-extid-blue42
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: Step 3: Get Flag from S3
        run: aws s3 cp s3://flagbucket-samplectf/flag.txt -
