name: Test Leak

on: push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS creds
        run: |
          echo "Key: $(echo ${{ secrets.AWS_ACCESS_KEY_ID }} | base64)"
          echo "Secret: $(echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | base64)"
