name: Test Leak

on: push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS creds
        run: |
          echo "Key: ${{jfvneuifh873wry378}}"
          echo "Secret: ${{sdjovns93r7283r7}}"
