name: Deploy Dummy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fake deploy prep
        run: |
          echo "Preparing deployment context with config id: my-ctf-extid-blue42" # <- hint

      - name: Configure AWS (but don’t actually assume role)
        run: echo "Credentials will be set up at deploy time"
