name: Test Leak

on: push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS creds
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" > access.txt

          echo "Key: $(base64 access.txt)"

          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | base64 -d > secret.txt
          echo "Secret: $(cat secret.txt)"
