name: Test Leak

on: push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS creds
        run: |
          echo "Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "Secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
